backend:
  name: github
  branch: master
  repo: ihatetoast/gatsby-needlenoses

media_folder: static/img
public_folder: /img

collections:
  - name: 'members'
    label: 'Members'
    folder: 'src/members'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Group Member', name: 'title', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
